select count(*) TOTAL_REGISTROS,
sum(case when length(trim(CUSTOMER_ID))<>0 then 1 else 0 end) TOTAL_CUSTOMER_ID,
count(distinct trim(CUSTOMER_ID)) DISTINC_CUSTOMER_ID,
sum(case when length(trim(FIRST_NAME))<>0 then 1 else 0 end) TOTAL_FIRST_NAME,
count(distinct (trim(FIRST_NAME))) DISTINC_FIRST_NAME,
sum(case when length(trim(LAST_NAME))<>0 then 1 else 0 end) TOTAL_LAST_NAME,
count(distinct (trim(LAST_NAME))) DISTINC_LAST_NAME,
sum(case when length(trim(IDENTIFIED_DOC))<>0 then 1 else 0 end) TOTAL_IDENTIFIED_DOC,
count(distinct (trim(IDENTIFIED_DOC))) DISTINC_IDENTIFIED_DOC,
sum(case when length(trim(GENDER))<>0 then 1 else 0 end) TOTAL_GENDER,
count(distinct (trim(GENDER))) DISTINC_GENDER,
sum(case when length(trim(CITY))<>0 then 1 else 0 end) TOTAL_CITY,
count(distinct (trim(CITY))) DISTINC_CITY,
sum(case when length(trim(ADDRESS))<>0 then 1 else 0 end) TOTAL_ADDRESS,
count(distinct (trim(ADDRESS))) DISTINC_ADDRESS,
sum(case when length(trim(POSTAL_CODE))<>0 then 1 else 0 end) TOTAL_POSTAL_CODE,
count(distinct (trim(POSTAL_CODE))) DISTINC_POSTAL_CODE,
sum(case when length(trim(STATE))<>0 then 1 else 0 end) TOTAL_STATE,
count(distinct (trim(STATE))) DISTINC_STATE,
sum(case when length(trim(COUNTRY))<>0 then 1 else 0 end) TOTAL_COUNTRY,
count(distinct (trim(COUNTRY))) DISTINC_COUNTRY,
sum(case when length(trim(PHONE))<>0 then 1 else 0 end) TOTAL_PHONE,
count(distinct (trim(PHONE))) DISTINC_PHONE,
sum(case when length(trim(EMAIL))<>0 then 1 else 0 end) TOTAL_EMAIL,
count(distinct (trim(EMAIL))) DISTINC_EMAIL,
sum(case when length(trim(BIRTHDAY))<>0 then 1 else 0 end) TOTAL_BIRTHDAY,
count(distinct (trim(BIRTHDAY))) DISTINC_BIRTHDAY,
sum(case when length(trim(PROFESION))<>0 then 1 else 0 end) TOTAL_PROFESION,
count(distinct (trim(PROFESION))) DISTINC_PROFESION
from STG.STG_CLIENTES_CRM;

