/*create database STG;*/
use STG;

DROP TABLE if exists STG_CLIENTES_CRM;
CREATE TABLE STG_CLIENTES_CRM AS 
SELECT * FROM CRM.CLIENTES;
analyze table STG_CLIENTES_CRM;

DROP TABLE if exists STG_ORDERS_CRM;
CREATE TABLE STG_ORDERS_CRM AS 
SELECT * FROM CRM.ORDERS;
analyze table STG_ORDERS_CRM;

DROP TABLE if exists STG_PRODUCTOS_CRM;
CREATE TABLE STG_PRODUCTOS_CRM AS 
SELECT * FROM CRM.PRODUCTOS;
analyze table STG_PRODUCTOS_CRM;

DROP TABLE if exists STG_FACTURAS_FACTURADOR;
CREATE TABLE STG_FACTURAS_FACTURADOR AS 
SELECT * FROM FACTURADOR.FACTURAS;
analyze table STG_FACTURAS_FACTURADOR;

DROP TABLE if exists STG_CONTACTOS_IVR;
CREATE TABLE STG_CONTACTOS_IVR AS 
SELECT * FROM IVR.CONTACTOS;
analyze table STG_CONTACTOS_IVR;